### ISSUE TITLE
Tests no longer pass on Rakudo HEAD

### ISSUE THREAD

**Issue by AlexDaniel** [jnthn/p6-test-scheduler#3]
Bisectable points at (2017-09-21) https://github.com/rakudo/rakudo/commit/9d903408e3727cb2dd26e78f92a8e0a12345907a

Output before and after:
https://gist.github.com/1bfc21bbe414128fe1f6e7529dce5f3e

Also, because of that issue [Concurrent::Progress](https://github.com/jnthn/p6-concurrent-progress) is no longer installable.

**Comment by AlexDaniel** [comment]
Also failing: [SSH:LibSSH](https://github.com/jnthn/p6-ssh-libssh) because it depends on [Concurrent::Progress](https://github.com/jnthn/p6-concurrent-progress) which depends on this module.

**Comment by AlexDaniel** [comment]
FWIW it hangs on that line:
https://github.com/jnthn/p6-test-scheduler/blob/37e80685b682f65b6c01d10f74469a4db1c93b29/t/virtualized-time.t#L167

**Comment by bbkr** [comment]
Same result here - testing hangs forever.
Rakudo 2017.10 + macOS 10.10.

**Comment by jnthn** [comment]
Curious bisect result; it's not immediately clear what's going wrong. Will try and get to looking at this soon.

**Comment by bbkr** [comment]
Still tests hang forever on 2017.11.

**Comment by tbrowder** [comment]
When testing with module Toaster, this module hangs and cannot be killed by the toaster job.

**Comment by bbkr** [comment]
Same on 2018.04.

@jnthn: If fix / debug is too consuming can this module be at least dropped temporarily from SSH:LibSSH dependencies?

**Comment by AlexDaniel** [comment]
Ping?

**Comment by AlexDaniel** [comment]
@bbkr fwiw you should be able to install it like this: ``zef install --/test Test::Scheduler``, though I don't know if it is functional.

**Comment by jnthn** [comment]
After various changes, the tests now pass again. Will want to give this module more attention in the future, but for now this gets it installing again.
